# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Set up yarn cache
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
              ${{ runner.os }}-node-

      - name: Write all git secrets to .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PAYLOAD_SECRET_KEY=${{ secrets.PAYLOAD_SECRET_KEY }}" > .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
          echo "NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}" >> .env
          echo "PORT=5000" >> .env

      - name: npm install, build, and test
        run: |
          yarn --production=false --frozen-lockfile --network-timeout 1000000000
          yarn build

      - name: zip artifact
        run: zip -r artifact.zip . -x .git/\* .github/\* .vscode/\* .next/cache/\*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Setup SSH deploy keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip -q artifact.zip

      - name: Deploy to Azure
        run: |
          ./deploy.sh --host ${{ secrets.SSH_HOST }} --user ${{ secrets.SSH_USER }} --port ${{ secrets.SSH_PORT }} --commit ${{ github.sha }}